name: CI / CD

on:
  push:
    branches:
      - main

permissions:
  contents: read    # for checkout
  packages: write   # to push to GHCR
  id-token: write   # if you use OIDC for Docker login

jobs:
  build-and-publish:
    name: Build & Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/jamesgibbs/laravel-app:prod

  deploy:
    name: Deploy to Production
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
#      - name: Install Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}     # default is 22
          key: ${{ secrets.SSH_KEY }}       # your private key
          script: |
            cd /var/www
            if [ ! -d ".git" ]; then
              git clone https://github.com/Jamesgibbs/cicd.git .
            else
              git pull origin main
            fi
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker compose -f docker-compose.prod.yml exec app php artisan migrate --force
